name=input("Enter your name:")
branch=input("Enter your branch:")
gender=input("Enter your gender:")
college=input("Enter the name of your college:")
age=input("Enter your age:")

print("Name is :",name)
print("Branch is: ",branch)
print("gender is: ",gender)
print("College is: ",college)
print("Age is: ",age)
